### ISSUE TITLE
Void variable left

### ISSUE THREAD

**Issue by mbsmith** [milkypostman/powerline#80] opened 2015-03-16 13:39 UTC
```
Debugger entered--Lisp error: (void-variable left)                                                                             
  powerline-reset()                                                                                                            
  require(powerline)                                                                                                           
  eval-buffer(#<buffer  *load*> nil "/home/xulfer/.emacs" nil t)  ; Reading at buffer position 5106                            
  load-with-code-conversion("/home/xulfer/.emacs" "/home/xulfer/.emacs" t t)                                                   
  load("~/.emacs" t t)                                                                                                         
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313$
  command-line()                                                                                                               
  normal-top-level()  
```

Happened after a recent update.  I saw a similar issue form 2013, but the trace is different so I'm assuming this is a new issue.

**Comment by milkypostman** [comment] 2015-03-16 21:09
Yeah, I need to look into this. It's happening because of the compilation and macro expansion and I don't fully know the intricacies of the problem.

**Comment by pronobis** [comment] 2015-03-18 18:17
Same problem here. This makes powerline unusable and interrupts my Emacs init. Could you please revert the commit that caused it until the problem is resolved?

**Comment by milkypostman** [comment] 2015-03-19 03:39
@pronobis are you using `use-package` as well? Could you send me the snippet of code that you are using to load and run powerline?

**Comment by liamoc** [comment] 2015-03-19 04:04
Argh, this has interrupted my init as well. I'm using spacemacs, which uses use-package internally i think. I did nothing regarding powerline that spacemacs doesn't do by default..

**Comment by milkypostman** [comment] 2015-03-19 04:31
@liamoc I can't understand what is happening here. I have tried 3 different emacs versions and cannot repro the problem. I event installed spacemacs...

**Comment by milkypostman** [comment] 2015-03-19 04:35
@liamoc @pronobis can I guess that you are both running 24.4.1?

**Comment by liamoc** [comment] 2015-03-19 04:37
Yup, 24.4.1.

I'm running the mac build recommended for spacemacs, https://github.com/railwaycat/emacs-mac-port

**Comment by liamoc** [comment] 2015-03-19 04:38
Simply rolling back powerline to the earlier version I had installed fixes the problem.

**Comment by milkypostman** [comment] 2015-03-19 04:46
@liamoc just as a favor to me, could you try upgrading to the newest mac port, and wiping your `.emacs.d/elpa` directory? Because I have just tried installing spacemacs on the emacs-mac-port and still have no problems. But I am working with a *clean* checkout of everything.

know that it takes a while but appreciate any time you spend on it.

**Comment by kimgronqvist** [comment] 2015-03-19 10:14
I had the same issue. 24.4.1 on Windows 8. I don't use use-package.

Removing the package from the elpa directory and then reinstalling worked for me.

**Comment by milkypostman** [comment] 2015-03-19 16:12
@liamoc @pronobis it sounds like you have some stale files in your path somewhere that is interfering. I don't know if `spacemacs` or `use-package` actually do cleanup on old packages.

**Comment by pronobis** [comment] 2015-03-19 18:01
I'm not exactly sure what happened, but standard elpa update (without removing any files manually) fixed things for me. I do have the old files for comparison in case you want to check them out.

**Comment by jasonm23** [comment] 2015-03-19 23:38
[pr 82](https://github.com/milkypostman/powerline/pull/82) was merged yesterday.

**Comment by fpz** [comment] 2015-04-01 09:54
I just ran into this issue after a standard elpa update. I had to delete all powerline *.elc files from powerline-20150319.533 in order to make it work. I'm running Cygwin version of Emacs 24.4.1.

**Comment by icymist** [comment] 2015-04-01 12:25
Suggestion by @fpz, removal of all *.elc files, works for me too. I am on opensuse 13.2, emacs 24.3.1.

**Comment by hunner** [comment] 2015-04-03 17:00
:+1: on deleting .elc files. Perhaps this issue should be closed then, as it does not really exist?

**Comment by jasonm23** [comment] 2015-04-03 17:08
Closing

**Closed by jasonm23** 2015-04-03 17:08 UTC

**Comment by lenage** [comment] 2015-04-11 17:16
I have same issue too, and it works after remove all `*.elc` files in `powerline` folde

**Comment by Mekk** [comment] 2015-11-03 07:17
I faced this too, after upgrading to powerline-20151008.1449 from powerline-2.2. Removing .elc files and restarting helped.

Note: those .elc files were NOT stalled.  Those were fresh new .elc files saved in fresh new powerline-20151008.1449 directory.  I am not sure what compiled those (most likely paradox-install-package).

My bet is that powerline compiles wrongly in presence of loaded old powerline version (and leaves broken .elc for future use). 

And my idea to reproduce the problem is:
→ install powerline-2.2 from melpa-stable (or maybe some other way), load it, and have it active
→ install new powerline FROM MELPA (so package system compiles it in the context where old powerline is active and working)

PS I am also use-package user, and I use powerline via other packages (faced this twice, first under smart-mode-line, then under spaceline), but I am not sure whether it is related.

**Comment by milkypostman** [comment] 2015-11-06 03:05
i bet you are totally right about the compilation i hadn't thought about
that. so weird.

maybe this is something worth filing an emacs bug about?

**Comment by Mekk** [comment] 2015-11-10 05:49
I doubt. Emacs in general claims that byte-compilation may misbehave unless done in clean environment…

From practical point of view this may be possible to solve on package level. Maybe some eval-when-compile, or maybe even renaming/aliasing some of those symbols…
